name: Build docker image

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/steamy-kanban-server:latest

      - uses: fdiesel/github-action-deploy-aws-lightsail-container@v3.0.1
        with:
          image-name: steamy-kanban-server
          image: ${{ secrets.DOCKER_USER }}/steamy-kanban-server:latest
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-lightsail-service: ${{ secrets.AWS_LIGHTSAIL_SERVICE }}
          aws-lightsail-service-config: ${{ secrets.AWS_LIGHTSAIL_SERVICE_CONFIG }}
          aws-lightsail-clear-images: false
