name: Build docker image

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/steamy-kanban-server:latest
            

    # uses: fdiesel/github-action-deploy-aws-lightsail-container@8b671d46048f37541346518e1eb847c81aeb2200
    #uses: fdiesel/github-action-deploy-aws-lightsail-container@v2.0.
          
