name: Build docker image

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          # Name of the Docker image
          name: steamy-kanban-server
          # Tag for the Docker image
          tag: $(date +%s)
          # Username for Docker registry
          username: ${secrets.DOCKER_USER}
          # Password for Docker registry
          password:  ${secrets.DOCKER_PASS}
          # Registry URL
          registry: "hub.docker.com"
          # Path to Dockerfile
          dockerfile path: .
            

    # uses: fdiesel/github-action-deploy-aws-lightsail-container@8b671d46048f37541346518e1eb847c81aeb2200
    #uses: fdiesel/github-action-deploy-aws-lightsail-container@v2.0.
          
